"""add mapped_field reason

Revision ID: 00dd6ce046ef
Revises: 517bdee01fa7
Create Date: 2026-09-07 17:10:40.969102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dd6ce046ef'
down_revision: Union[str, Sequence[str], None] = '517bdee01fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapped_fields', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapped_fields', 'reason')
    # ### end Alembic commands ###
