"""add execution seen flag

Revision ID: 0dd059614a93
Revises: 00dd6ce046ef
Create Date: 2026-09-07 18:07:33.131472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd059614a93'
down_revision: Union[str, Sequence[str], None] = '00dd6ce046ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # las ejecuciones existentes quedan "vistas" (no generan de golpe un backlog de
    # notificaciones sin ver); las nuevas parten en False via el default de la app.
    op.add_column(
        'executions',
        sa.Column('seen', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('executions', 'seen', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'seen')
    # ### end Alembic commands ###
