"""drop workflow confidence_threshold

Revision ID: 4e2854d22d5b
Revises: 54ec0ab4a714
Create Date: 2026-09-07 16:17:50.932292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2854d22d5b'
down_revision: Union[str, Sequence[str], None] = '54ec0ab4a714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'confidence_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('confidence_threshold', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
