"""add workflow field_thresholds

Revision ID: 517bdee01fa7
Revises: 4e2854d22d5b
Create Date: 2026-09-07 16:38:54.460183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517bdee01fa7'
down_revision: Union[str, Sequence[str], None] = '4e2854d22d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workflows',
        sa.Column('field_thresholds', sa.JSON(), nullable=False, server_default='{}'),
    )
    op.alter_column('workflows', 'field_thresholds', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'field_thresholds')
    # ### end Alembic commands ###
