"""add execution confidence_threshold_used

Revision ID: 54ec0ab4a714
Revises: eef6b5975fe5
Create Date: 2026-09-07 15:43:20.835664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ec0ab4a714'
down_revision: Union[str, Sequence[str], None] = 'eef6b5975fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('confidence_threshold_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'confidence_threshold_used')
    # ### end Alembic commands ###
