"""drop unused mapped_fields.evidence_json

Revision ID: 5530a311f9cd
Revises: ebfefe92d40f
Create Date: 2026-09-07 13:26:31.725996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5530a311f9cd'
down_revision: Union[str, Sequence[str], None] = 'ebfefe92d40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapped_fields', 'evidence_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapped_fields', sa.Column('evidence_json', sa.NVARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
