"""add reference_document_id to document_type_versions

Revision ID: 66b8ec091cae
Revises: d19f11a7cad3
Create Date: 2026-09-04 13:48:00.652994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b8ec091cae'
down_revision: Union[str, Sequence[str], None] = 'd19f11a7cad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_type_versions', sa.Column('reference_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_type_versions', 'documents', ['reference_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_type_versions', type_='foreignkey')
    op.drop_column('document_type_versions', 'reference_document_id')
    # ### end Alembic commands ###
