"""add extraction_schema and mapped_field data_type

Revision ID: 9abc5fde8779
Revises: cba2a3be310b
Create Date: 2026-09-07 13:06:17.676925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abc5fde8779'
down_revision: Union[str, Sequence[str], None] = 'cba2a3be310b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_type_versions', sa.Column('extraction_schema', sa.JSON(), nullable=True))
    op.add_column(
        'mapped_fields',
        sa.Column('data_type', sa.String(length=20), nullable=False, server_default='texto'),
    )
    op.alter_column('mapped_fields', 'data_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapped_fields', 'data_type')
    op.drop_column('document_type_versions', 'extraction_schema')
    # ### end Alembic commands ###
