"""add mapped_field resolved flag

Revision ID: eade54f2a6f4
Revises: f595b5ca1750
Create Date: 2026-09-08 09:46:21.867594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eade54f2a6f4'
down_revision: Union[str, Sequence[str], None] = 'f595b5ca1750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'mapped_fields',
        sa.Column('resolved', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('mapped_fields', 'resolved', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapped_fields', 'resolved')
    # ### end Alembic commands ###
