"""add execution model_response_json

Revision ID: ebc8717b8832
Revises: eade54f2a6f4
Create Date: 2026-09-08 10:25:22.676422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc8717b8832'
down_revision: Union[str, Sequence[str], None] = 'eade54f2a6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('model_response_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'model_response_json')
    # ### end Alembic commands ###
