"""drop unused alerts table and executions.is_preview

Revision ID: ebfefe92d40f
Revises: 9abc5fde8779
Create Date: 2026-09-07 13:21:03.444385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'ebfefe92d40f'
down_revision: Union[str, Sequence[str], None] = '9abc5fde8779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_column('executions', 'is_preview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('is_preview', mssql.BIT(), autoincrement=False, nullable=False))
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('resolved', mssql.BIT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('FK__alerts__executio__7C4F7684')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__alerts__3213E83F2A06FAEB'))
    )
    # ### end Alembic commands ###
