"""drop description from document_types

Revision ID: edca159aa110
Revises: 66b8ec091cae
Create Date: 2026-09-04 14:13:31.510210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edca159aa110'
down_revision: Union[str, Sequence[str], None] = '66b8ec091cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('description', sa.VARCHAR(length=1000, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
