"""add workflow trigger_type

Revision ID: eef6b5975fe5
Revises: 5530a311f9cd
Create Date: 2026-09-07 14:56:47.611883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef6b5975fe5'
down_revision: Union[str, Sequence[str], None] = '5530a311f9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workflows',
        sa.Column('trigger_type', sa.String(length=30), nullable=False, server_default='manual'),
    )
    op.alter_column('workflows', 'trigger_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'trigger_type')
    # ### end Alembic commands ###
